"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import SafeAppsSDK from "@safe-global/safe-apps-sdk";
import { formatUnits } from "viem";
import {
  buildSafeTxBuilderJson,
  copyToClipboard,
  isSafeContext,
  proposeSafeBatch,
  type SafeInfo,
} from "@/utils/adminBatchTx";
import {
  buildMaidenVoyageTransferCalls,
  sumPayoutUsd,
  sumPayoutWei,
  type MaidenVoyagePayoutRow,
} from "@/utils/maidenVoyagePayouts";
import { TREASURY_SAFE_ADDRESS } from "@/config/treasury";
import type { Address } from "viem";

type Props = {
  marketLabel: string;
  collateralSymbol: string;
  wrappedToken: Address;
  payoutRows: MaidenVoyagePayoutRow[];
  collateralPriceUSD: number;
  priceError: string | null;
  tokenDecimals: number;
  treasuryBalance: bigint | undefined;
  balanceLoading: boolean;
  disabled?: boolean;
  onRecordLedger?: (
    safeTxHash: string | undefined,
    rows: MaidenVoyagePayoutRow[]
  ) => Promise<void>;
};

function truncate(addr: string) {
  return addr.length > 12 ? `${addr.slice(0, 6)}…${addr.slice(-4)}` : addr;
}

export function MaidenVoyageDistributeRewards({
  marketLabel,
  collateralSymbol,
  wrappedToken,
  payoutRows,
  collateralPriceUSD,
  priceError,
  tokenDecimals,
  treasuryBalance,
  balanceLoading,
  disabled,
  onRecordLedger,
}: Props) {
  const [modalOpen, setModalOpen] = useState(false);
  const [recordLedger, setRecordLedger] = useState(true);
  const [proposing, setProposing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<string | null>(null);
  const [safeInfo, setSafeInfo] = useState<SafeInfo | null>(null);

  useEffect(() => {
    if (!isSafeContext()) return;
    let mounted = true;
    void (async () => {
      try {
        const sdk = new SafeAppsSDK();
        const info = await sdk.safe.getInfo();
        if (!mounted) return;
        setSafeInfo({
          safeAddress: info.safeAddress as `0x${string}`,
          chainId: info.chainId,
        });
      } catch {
        // ignore
      }
    })();
    return () => {
      mounted = false;
    };
  }, []);

  const txs = useMemo(
    () =>
      buildMaidenVoyageTransferCalls(
        wrappedToken,
        payoutRows,
        collateralSymbol
      ),
    [wrappedToken, payoutRows, collateralSymbol]
  );

  const totalWei = useMemo(() => sumPayoutWei(payoutRows), [payoutRows]);
  const totalUsd = useMemo(() => sumPayoutUsd(payoutRows), [payoutRows]);
  const totalFormatted = formatUnits(totalWei, tokenDecimals);

  const insufficientBalance =
    treasuryBalance !== undefined && totalWei > treasuryBalance;

  const canDistribute =
    !disabled &&
    payoutRows.length > 0 &&
    !priceError &&
    collateralPriceUSD > 0 &&
    totalWei > 0n &&
    !insufficientBalance &&
    !balanceLoading;

  const safeTxBuilderJson = useMemo(
    () =>
      buildSafeTxBuilderJson(txs, {
        name: `Harbor: Maiden Voyage Yield — ${marketLabel}`,
        description:
          "ERC20 transfers from Treasury Safe to maiden voyage participants. Generated by Harbor admin UI.",
      }),
    [txs, marketLabel]
  );

  const handleCopyJson = useCallback(() => {
    copyToClipboard(safeTxBuilderJson);
    setResult("Copied Safe Transaction Builder JSON.");
  }, [safeTxBuilderJson]);

  const handlePropose = useCallback(async () => {
    setError(null);
    setResult(null);
    setProposing(true);
    try {
      const res = await proposeSafeBatch(txs, safeInfo);
      if (!res.ok) {
        setError(res.error);
        return;
      }
      const hashMsg = res.safeTxHash
        ? `Proposed Safe transaction: ${res.safeTxHash}`
        : "Proposed Safe transaction.";
      setResult(hashMsg);

      if (recordLedger && onRecordLedger) {
        try {
          await onRecordLedger(res.safeTxHash, payoutRows);
          setResult(`${hashMsg} Ledger updated.`);
        } catch (e: unknown) {
          setError(
            e instanceof Error
              ? `Safe proposed, but ledger record failed: ${e.message}`
              : "Safe proposed, but ledger record failed."
          );
        }
      }
      setModalOpen(false);
    } finally {
      setProposing(false);
    }
  }, [txs, safeInfo, recordLedger, onRecordLedger, payoutRows]);

  const largeBatchWarning = txs.length > 30;

  return (
    <>
      <button
        type="button"
        onClick={() => {
          setError(null);
          setResult(null);
          setModalOpen(true);
        }}
        disabled={!canDistribute}
        className="py-2 px-4 bg-emerald-700 text-white text-sm disabled:opacity-50 hover:bg-emerald-600 transition-colors"
        title={
          !canDistribute
            ? priceError ||
              (payoutRows.length === 0
                ? "No payable outstanding rows"
                : insufficientBalance
                  ? "Treasury balance too low"
                  : "Cannot distribute")
            : undefined
        }
      >
        Distribute rewards
      </button>
      {result && !modalOpen && (
        <p className="text-green-400 text-xs mt-2 max-w-xl">{result}</p>
      )}

      {modalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70">
          <div className="bg-zinc-900 border border-white/10 max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col rounded-md">
            <div className="p-4 sm:p-6 border-b border-white/10">
              <h3 className="text-lg font-medium text-white font-geo">
                Distribute rewards — {marketLabel}
              </h3>
              <p className="text-xs text-white/60 mt-2">
                Proposes a Treasury Safe batch of{" "}
                <span className="text-white/80">{collateralSymbol}</span>{" "}
                transfers ({truncate(wrappedToken)}). Price: $
                {collateralPriceUSD.toFixed(4)} / token. Treasury:{" "}
                <span className="font-mono">{TREASURY_SAFE_ADDRESS}</span>
              </p>
              <p className="text-xs text-amber-200/90 mt-2">
                Tokens move only after the Safe transaction is executed. If you
                record the ledger at propose time, it reflects intent to pay
                (Safe tx hash may still be pending).
              </p>
              {safeInfo ? (
                <p className="text-xs text-white/50 mt-1">
                  Safe context: {safeInfo.safeAddress} (chain {safeInfo.chainId})
                </p>
              ) : (
                <p className="text-xs text-white/50 mt-1">
                  Not in Safe iframe — use Copy Safe JSON or open this admin page
                  in the Treasury Safe app.
                </p>
              )}
            </div>

            <div className="p-4 sm:p-6 overflow-y-auto flex-1 space-y-4">
              <div className="grid sm:grid-cols-3 gap-3 text-sm">
                <div className="bg-black/30 p-3 rounded">
                  <div className="text-white/50 text-xs">Recipients</div>
                  <div className="text-white font-mono">{payoutRows.length}</div>
                </div>
                <div className="bg-black/30 p-3 rounded">
                  <div className="text-white/50 text-xs">Total ({collateralSymbol})</div>
                  <div className="text-white font-mono">{totalFormatted}</div>
                  <div className="text-white/50 text-xs">
                    ≈ ${totalUsd.toFixed(2)} USD outstanding
                  </div>
                </div>
                <div className="bg-black/30 p-3 rounded">
                  <div className="text-white/50 text-xs">Treasury balance</div>
                  <div className="text-white font-mono">
                    {balanceLoading
                      ? "…"
                      : treasuryBalance !== undefined
                        ? formatUnits(treasuryBalance, tokenDecimals)
                        : "—"}
                  </div>
                </div>
              </div>

              {insufficientBalance && (
                <p className="text-red-400 text-sm">
                  Total payout exceeds Treasury {collateralSymbol} balance.
                </p>
              )}
              {largeBatchWarning && (
                <p className="text-amber-200 text-sm">
                  Large batch ({txs.length} calls) — confirm gas limits in Safe
                  before executing.
                </p>
              )}
              {error && <p className="text-red-400 text-sm">{error}</p>}

              <label className="flex items-center gap-2 text-sm text-white/80 cursor-pointer">
                <input
                  type="checkbox"
                  checked={recordLedger}
                  onChange={(e) => setRecordLedger(e.target.checked)}
                  className="rounded"
                />
                Record in ledger after proposing (per-wallet outstanding USD)
              </label>

              <div className="overflow-x-auto max-h-64 border border-white/10">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-left text-white/60 border-b border-white/10 bg-zinc-950">
                      <th className="py-2 px-2">Wallet</th>
                      <th className="py-2 px-2 text-right">Outstanding USD</th>
                      <th className="py-2 px-2 text-right">Pay ({collateralSymbol})</th>
                    </tr>
                  </thead>
                  <tbody>
                    {payoutRows.map((r) => (
                      <tr key={r.wallet} className="border-t border-white/5">
                        <td className="py-1.5 px-2 font-mono text-white/90">
                          {truncate(r.wallet)}
                        </td>
                        <td className="py-1.5 px-2 text-right font-mono">
                          {r.outstanding.toFixed(2)}
                        </td>
                        <td className="py-1.5 px-2 text-right font-mono">
                          {formatUnits(r.amountWei, tokenDecimals)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="p-4 sm:p-6 border-t border-white/10 flex flex-wrap gap-2 justify-end">
              <button
                type="button"
                onClick={() => setModalOpen(false)}
                className="py-2 px-4 bg-zinc-700 text-white text-sm"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleCopyJson}
                disabled={txs.length === 0}
                className="py-2 px-4 bg-white/10 text-white text-sm disabled:opacity-50"
              >
                Copy Safe JSON
              </button>
              <button
                type="button"
                onClick={() => void handlePropose()}
                disabled={proposing || !canDistribute}
                className="py-2 px-4 bg-emerald-700 text-white text-sm disabled:opacity-50"
              >
                {proposing ? "Proposing…" : "Propose Safe batch"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
