/**
 * Minter USDC Zap V3 – full ABI from deployed contract.
 * Includes permit + stability pool zaps and custom errors (SlippageExceeded, NoFxSaveReceived, etc.)
 * for accurate revert decoding.
 */
export const MINTER_USDC_ZAP_V3_ABI = [
  { inputs: [{ internalType: "address", name: "minter_", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [{ internalType: "address", name: "target", type: "address" }], name: "AddressEmptyCode", type: "error" },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  { inputs: [], name: "CannotCompleteTransfer", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "CannotRescueProtectedToken", type: "error" },
  { inputs: [{ internalType: "address", name: "expected", type: "address" }, { internalType: "address", name: "actual", type: "address" }], name: "CollateralMismatch", type: "error" },
  { inputs: [], name: "DepositFailed", type: "error" },
  { inputs: [{ internalType: "address", name: "implementation", type: "address" }], name: "ERC1967InvalidImplementation", type: "error" },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  { inputs: [], name: "FunctionNotFound", type: "error" },
  { inputs: [{ internalType: "uint256", name: "have", type: "uint256" }, { internalType: "uint256", name: "wanted", type: "uint256" }], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "MintFailed", type: "error" },
  { inputs: [], name: "NoFxSaveReceived", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "spender", type: "address" }, { internalType: "uint256", name: "currentAllowance", type: "uint256" }, { internalType: "uint256", name: "requestedDecrease", type: "uint256" }], name: "SafeERC20FailedDecreaseAllowance", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  { inputs: [], name: "SlippageExceeded", type: "error" },
  { inputs: [], name: "StabilityPoolNotAllowed", type: "error" },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }], name: "UUPSUnsupportedProxiableUUID", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "peggedOut", type: "uint256" },
      { indexed: false, internalType: "address", name: "stabilityPool", type: "address" },
      { indexed: false, internalType: "uint256", name: "deposited", type: "uint256" },
    ],
    name: "FXSAVEZappedToStabilityPool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "leveragedOut", type: "uint256" },
    ],
    name: "FXUSDZappedToLeveraged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "peggedOut", type: "uint256" },
    ],
    name: "FXUSDZappedToPegged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "peggedOut", type: "uint256" },
      { indexed: false, internalType: "address", name: "stabilityPool", type: "address" },
      { indexed: false, internalType: "uint256", name: "deposited", type: "uint256" },
    ],
    name: "FXUSDZappedToStabilityPool",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }], name: "Initialized", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "stabilityPool", type: "address" },
      { indexed: false, internalType: "bool", name: "allowed", type: "bool" },
    ],
    name: "StabilityPoolAllowlistUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "leveragedOut", type: "uint256" },
    ],
    name: "USDCZappedToLeveraged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "peggedOut", type: "uint256" },
    ],
    name: "USDCZappedToPegged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "address", name: "minter", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { indexed: false, internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "peggedOut", type: "uint256" },
      { indexed: false, internalType: "address", name: "stabilityPool", type: "address" },
      { indexed: false, internalType: "uint256", name: "deposited", type: "uint256" },
    ],
    name: "USDCZappedToStabilityPool",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }], name: "Upgraded", type: "event" },
  { stateMutability: "payable", type: "fallback" },
  { inputs: [], name: "FXSAVE", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "FXUSD", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "FXUSD_DIAMOND", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "FXUSD_SWAP_ROUTER", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "MINTER", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "UPGRADE_INTERFACE_VERSION", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "USDC", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "allowedStabilityPools", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "address", name: "deployerOwner", type: "address" }, { internalType: "address", name: "pendingOwner", type: "address" }],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "owner_", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "fxSaveAmount", type: "uint256" }], name: "previewLeveragedFromFxSave", outputs: [{ internalType: "uint256", name: "leveragedOut", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "fxSaveAmount", type: "uint256" }], name: "previewPeggedFromFxSave", outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "fxSaveAmount", type: "uint256" }], name: "previewStabilityPoolFromFxSave", outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "proxiableUUID", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "rescueEth", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "rescueToken", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "stabilityPool", type: "address" }, { internalType: "bool", name: "allowed", type: "bool" }], name: "setStabilityPoolAllowed", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }], name: "supportsInterface", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "confirmOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newImplementation", type: "address" }, { internalType: "bytes", name: "data", type: "bytes" }], name: "upgradeToAndCall", outputs: [], stateMutability: "payable", type: "function" },
  {
    inputs: [
      { internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
    ],
    name: "zapFxSaveToStabilityPool",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxSaveAmount", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapFxSaveToStabilityPoolWithPermit",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minLeveragedOut", type: "uint256" },
    ],
    name: "zapFxUsdToLeveraged",
    outputs: [{ internalType: "uint256", name: "leveragedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minLeveragedOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapFxUsdToLeveragedWithPermit",
    outputs: [{ internalType: "uint256", name: "leveragedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
    ],
    name: "zapFxUsdToPegged",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapFxUsdToPeggedWithPermit",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
    ],
    name: "zapFxUsdToStabilityPool",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fxUsdAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapFxUsdToStabilityPoolWithPermit",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "zapName", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minLeveragedOut", type: "uint256" },
    ],
    name: "zapUsdcToLeveraged",
    outputs: [{ internalType: "uint256", name: "leveragedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minLeveragedOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapUsdcToLeveragedWithPermit",
    outputs: [{ internalType: "uint256", name: "leveragedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
    ],
    name: "zapUsdcToPegged",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapUsdcToPeggedWithPermit",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
    ],
    name: "zapUsdcToStabilityPool",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "usdcAmount", type: "uint256" },
      { internalType: "uint256", name: "minFxSaveOut", type: "uint256" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "minPeggedOut", type: "uint256" },
      { internalType: "address", name: "stabilityPool", type: "address" },
      { internalType: "uint256", name: "minStabilityPoolOut", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "zapUsdcToStabilityPoolWithPermit",
    outputs: [{ internalType: "uint256", name: "peggedOut", type: "uint256" }, { internalType: "uint256", name: "deposited", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
