"use client";

import { useMemo, useState } from "react";
import {
  estimateMaidenVoyageOwnershipPct,
  estimateMaidenVoyageYieldSharePct,
  formatMaidenVoyageYieldSharePct,
} from "@/utils/maidenVoyageYieldShareEstimate";
import { GenesisFoundingPositionCards } from "./GenesisFoundingPositionCards";
import { GenesisFoundingPositionExplainer } from "./GenesisFoundingPositionExplainer";
import {
  MV_ACCENT_GRADIENT,
  MV_BODY_TEXT,
  MV_CAPTION_TEXT,
  MV_CARD_INNER_GRADIENT,
  MV_CARD_SHELL,
} from "./maidenVoyageLayoutStyles";

export type GenesisRevenueShareCalculatorProps = {
  capUsd: number | null;
  yieldRevSharePct: number | null;
  initialDepositUsd: number;
  className?: string;
};

function clampDeposit(value: number, capUsd: number | null): number {
  const max = capUsd ?? 10_000_000;
  return Math.min(max, Math.max(0, value));
}

export function GenesisRevenueShareCalculator({
  capUsd,
  yieldRevSharePct,
  initialDepositUsd,
  className = "",
}: GenesisRevenueShareCalculatorProps) {
  const [depositUsd, setDepositUsd] = useState(initialDepositUsd);

  const ownershipPct = useMemo(
    () => estimateMaidenVoyageOwnershipPct({ depositUsd, capUsd }),
    [depositUsd, capUsd],
  );

  const revenueSharePct = useMemo(
    () =>
      estimateMaidenVoyageYieldSharePct({
        depositUsd,
        capUsd,
        yieldRevSharePct,
      }),
    [depositUsd, capUsd, yieldRevSharePct],
  );

  const revenueShareLabel = formatMaidenVoyageYieldSharePct(revenueSharePct);

  return (
    <section
      className={`${MV_CARD_SHELL} ${MV_CARD_INNER_GRADIENT} w-full px-4 py-4 sm:px-5 sm:py-5 ${className}`.trim()}
      aria-label="Explore the upside"
    >
      <div className="min-w-0">
        <h2 className="text-sm font-semibold text-white/90 sm:text-base">
          Explore the Upside
        </h2>
        {yieldRevSharePct != null && yieldRevSharePct > 0 ? (
          <p className={`mt-0.5 ${MV_CAPTION_TEXT}`}>
            Every Maiden Voyage allocates {yieldRevSharePct}% of market revenue
            to founding participants.
          </p>
        ) : null}
      </div>

      <div className="mt-4 space-y-4">
        <p className="text-sm font-semibold text-white/90">Your Founding Position</p>

        <GenesisFoundingPositionCards
          depositUsd={depositUsd}
          ownershipPct={ownershipPct}
          revenueSharePct={revenueSharePct}
          onDepositChange={(v) => setDepositUsd(clampDeposit(v, capUsd))}
        />

        <p className={`text-center ${MV_BODY_TEXT}`}>
          You would own{" "}
          <span className={`font-mono font-semibold tabular-nums ${MV_ACCENT_GRADIENT}`}>
            {revenueShareLabel}
          </span>{" "}
          of all future revenue generated by this market, subject to maintaining
          eligibility.
        </p>

        <GenesisFoundingPositionExplainer
          depositUsd={depositUsd}
          capUsd={capUsd}
          ownershipPct={ownershipPct}
          revenueSharePct={revenueSharePct}
          yieldRevSharePct={yieldRevSharePct}
        />
      </div>
    </section>
  );
}
