import { TIDE_CONFIG } from "@/config/tide";
import { TREASURY_SAFE_ADDRESS } from "@/config/treasury";

/** Default maiden-voyage owner share (bps) used to gross-up pool revenue. */
export const MAIDEN_VOYAGE_YIELD_OWNER_SHARE_BPS = 500;

export const TIDE_FLYWHEEL_CONFIG = {
  tideTokenAddress: TIDE_CONFIG.tideTokenAddress,
  /** Set when treasury POL LP is known (Uniswap V2 pair); null if using v4 POL config. */
  polLpAddress: null as `0x${string}` | null,
  /** Uniswap v4 POL pool — treasury concentrated liquidity positions. */
  polV4: {
    poolId:
      "0x7c2a7ae6e86055412f6e2663797fcf77d669b9671cd016fe7230883e1a627196" as `0x${string}`,
    positionManagerAddress:
      "0xbd216513d74c8cf14cf4747e6aaa6420ff64ee9e" as `0x${string}`,
    stateViewAddress:
      "0x7ffe42c4a5deea5b0fec41c94c136cf115597227" as `0x${string}`,
    /** Scan from Uniswap v4 mainnet deployment block. */
    positionScanFromBlock: 21_600_000,
    uniswapPoolUrl:
      "https://app.uniswap.org/explore/pools/ethereum/0x7c2a7ae6e86055412f6e2663797fcf77d669b9671cd016fe7230883e1a627196",
  },
  treasuryAddress: TREASURY_SAFE_ADDRESS,
  tideDecimals: TIDE_CONFIG.tideDecimals,
  chainId: TIDE_CONFIG.chainId,
  targets: {
    treasuryOwnershipPct: 30,
    polOwnershipPct: 15,
  },
  buybackShareOfRevenuePct: 25,
  /** Buybacks are ongoing — no cumulative cap (25% of revenue per period). */
  buybackHasCap: false,
  /** Static until buyback indexing exists. */
  staticBuyback: {
    tideTokens: 0,
    /** If 0, derived from estimated revenue × buybackShareOfRevenuePct in hook. */
    usd: 0,
  },
  /**
   * Burn sink for on-chain supply-burned reads (e.g. dead address).
   * Set with tideTokenAddress to compute burned % live.
   */
  burnAddress: null as `0x${string}` | null,
  /** Static until burn indexing exists. */
  staticBurn: {
    /** Whole-percent display when on-chain burn read is unavailable. */
    supplyBurnedPct: 0,
    /** Optional wei-scale override; used with totalSupply when token is configured. */
    tideTokensBurned: 0,
  },
  copy: {
    titlePrimary: "The TIDE",
    titleAccent: "Flywheel",
    revenuePillLabel: "Revenue Generated (All Time)",
    steps: {
      buybacks: {
        title: "TIDE Buybacks",
        description: "25% of revenue buys back TIDE from the market.",
        statLabel: "TIDE Bought Back",
        footer: "Ongoing — no buyback cap",
      },
      treasury: {
        title: "Treasury Ownership",
        description:
          "Buybacks are added to the Treasury until it holds 30% of total TIDE supply.",
        statLabel: "Current Ownership",
        targetLabel: "Target: 30%",
        targetReached: "Target Reached",
      },
      pol: {
        title: "Protocol Owned Liquidity (POL)",
        description:
          "With >30% in Treasury, 100% of buybacks are added to POL.",
        statLabel: "POL Ownership",
        targetLabel: "Target: 15%",
        pendingConfig: "Pending LP configuration",
      },
      burn: {
        title: "Burn TIDE",
        description: "Once POL reaches 15%, excess TIDE is burned forever.",
        statLabel: "Supply Burned",
        footer: "Share of total TIDE supply permanently removed",
      },
    },
    footer: {
      aboutTitle: "About the Flywheel",
      aboutBody:
        "The TIDE Flywheel ensures protocol revenue continuously strengthens the ecosystem — first by securing ownership, then by building deep liquidity, and finally by reducing supply forever.",
      takeawayTitle: "Key Takeaway",
      takeawayBody:
        "Revenue generated by Harbor works for the ecosystem. The more we grow, the stronger TIDE becomes.",
    },
  },
} as const;

export type TideFlywheelStage = "treasury" | "pol" | "burn";
