/**
 * Primary "Manage" action on Genesis / Sail / Anchor index rows — one visual system.
 * Composed from {@link harborButtonStyles} tiers.
 */
import {
  HARBOR_BTN_CORAL_DESKTOP_CLASS,
  HARBOR_BTN_OUTLINE_DESKTOP_CLASS,
  HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS,
  HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS,
  HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS,
} from "@/components/shared/harborButtonStyles";

export const INDEX_MANAGE_BUTTON_CLASS_DESKTOP = HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS;

export const INDEX_WITHDRAW_BUTTON_CLASS_DESKTOP_CORAL = HARBOR_BTN_CORAL_DESKTOP_CLASS;

export const INDEX_MODAL_CANCEL_BUTTON_CLASS_DESKTOP = HARBOR_BTN_OUTLINE_DESKTOP_CLASS;

export const INDEX_MANAGE_BUTTON_CLASS_COMPACT = HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS;

export const INDEX_MANAGE_BUTTON_CLASS_RESPONSIVE = HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_COMPACT = HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_DESKTOP = HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_RESPONSIVE = HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS;
