/**
 * Primary "Manage" action on Genesis / Sail / Anchor (Earn) index rows — one visual system.
 * Uses `app-index-manage-btn`; MegaETH theme overrides in globals.css.
 */
import {
  HARBOR_BTN_CORAL_DESKTOP_CLASS,
  HARBOR_BTN_OUTLINE_DESKTOP_CLASS,
  HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS,
  HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS,
  HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS,
  HARBOR_BTN_SOLID_CORAL_COMPACT_PILL_CLASS,
  HARBOR_BTN_SOLID_CORAL_DESKTOP_CLASS,
  HARBOR_BTN_SOLID_CORAL_PILL_CLASS,
} from "@/components/shared/harborButtonStyles";

export const INDEX_MANAGE_BUTTON_CLASS_DESKTOP = HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS;

export const INDEX_WITHDRAW_BUTTON_CLASS_DESKTOP_CORAL = HARBOR_BTN_CORAL_DESKTOP_CLASS;

export const INDEX_EARN_CLAIM_BUTTON_CLASS_DESKTOP = HARBOR_BTN_SOLID_CORAL_DESKTOP_CLASS;

export const INDEX_EARN_CLAIM_BUTTON_CLASS_PILL = HARBOR_BTN_SOLID_CORAL_PILL_CLASS;

export const INDEX_EARN_CLAIM_BUTTON_CLASS_COMPACT = HARBOR_BTN_SOLID_CORAL_COMPACT_PILL_CLASS;

export const INDEX_MODAL_CANCEL_BUTTON_CLASS_DESKTOP = HARBOR_BTN_OUTLINE_DESKTOP_CLASS;

export const INDEX_MANAGE_BUTTON_CLASS_COMPACT = HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS;

export const INDEX_MANAGE_BUTTON_CLASS_RESPONSIVE = HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_COMPACT = HARBOR_BTN_PRIMARY_COMPACT_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_DESKTOP = HARBOR_BTN_PRIMARY_DESKTOP_WITH_APP_CLASS;

export const INDEX_CLAIM_BUTTON_CLASS_RESPONSIVE = HARBOR_BTN_PRIMARY_RESPONSIVE_WITH_APP_CLASS;
