/** Shared Earn/Sail chrome tokens for Genesis advanced layout. */
export {
  MARKET_SELECTOR_FIELD_LABEL_CLASS,
  MARKET_SELECTOR_ICON_SIZE,
  MARKET_SELECTOR_PAIR_FIELD_CLASS,
  MARKET_SELECTOR_ROW_CLASS,
  MARKET_SELECTOR_TOKEN_FIELD_CLASS,
  MARKET_SELECTOR_TRIGGER_CLASS,
  MARKET_SELECTOR_TRIGGER_INNER_CLASS,
  MARKET_SELECTOR_TRIGGER_TITLE_CLASS,
  SAIL_ADVANCED_FROSTED_LIGHT_PANEL,
  SAIL_ADVANCED_HEADER_STRIP_DIVIDE,
  SAIL_ADVANCED_HEADER_STRIP_LABEL,
  SAIL_ADVANCED_HEADER_STRIP_SHELL,
  SAIL_ADVANCED_HEADER_STRIP_VALUE,
  SAIL_ADVANCED_LABEL,
  SAIL_ADVANCED_LIGHT_BODY,
  SAIL_ADVANCED_LIGHT_SECTION_TITLE,
  SAIL_ADVANCED_MAIN_GRID_CLASS,
  SAIL_EMBEDDED_FORM_PANEL,
  SAIL_EMBEDDED_PANEL_HEIGHT,
} from "@/components/sail/advanced/sailAdvancedStyles";

export { DEPOSIT_TRADE_PANEL_GRID_CLASS } from "@/components/deposit/depositFlowStyles";

export const GENESIS_TRADE_PANEL_ID = "genesis-trade-panel";
